### PR TITLE
Log

### PR DESCRIPTION
**Pull request by abushev**
Attempt to disable debug in release build.
But maybe log level should be config param and passed into init_framework_logging function?

### CODE REVIEW

**Comment by venediktov** [comment]
Looks like Travis build fails in DEBUG mode with  "internal compiler error".

**Comment by abushev** [comment]
Yeah, and that's strange, cause in last commit only code under comment was deleted. 
Is there any way to force travis to rebuild this commit?

Anyway, do you think it is correct way to mute logging or may be config param like debug_level is better. Or may be something else?

**Comment by venediktov** [comment]
I just re-built , looks good now

**Comment by venediktov** [comment]
we'll try this way to mute if it does not work , we'll change it later

**Comment by venediktov** [comment]
I will Squash merge now.
Looks good to me , thank you !

**Pull request merged**
