### PR TITLE
experimental  bidder assembly API 

### PR DESCRIPTION
**Pull request by venediktov**
We have chained_selector trait class to delegate calls from one cache lookup to the next , the return of a lookup becomes input to the next cache lookup.

Outstanding issues \: 
- needs campaign generated data to test new assembly line 
- improve chained_selector class by removing repeated **BidRequest** , **Impression** as **typename ...Args**, 
but leaving main aka HeadArg as **typename Arg**

This pull request should close issue #74

### CODE REVIEW

**Comment by abushev** [comment]
Everything looks good.
But after using referer domain instead of referer url, which makes more sence, its good to rename all the related stuff like referer.hpp, ref_id in ico_campaign.hpp e.t.c to avoid misinform.
What do you think?

**Comment by venediktov** [comment]
I thought about it when fixing . It is still referer domain . Domain belongs to referer , right ? If I name class as domain.hpp then are we intend to use it for any domain matching in request ? If so then yes it seems better renaming to domain.hpp

**Comment by abushev** [comment]
Yea, I think the idea is to make targetings by domain, no matter was it get from referer or any other url.

**Comment by abushev** [comment]
Great job done!

**Pull request merged**
