### PR TITLE
Banker interface implementation 

### PR DESCRIPTION
**Pull request by venediktov**
Arseniy - need your inputs on formulas , not sure I got it right 
Vlad - please look at design and formulas for CPM/CPC

### CODE REVIEW

**Comment by venediktov** [comment]
This pull request should address issue #9

**Comment by venediktov** [comment]
@abushev , maybe 0 is better then exception , as currently CPA is not coded , so we'll get a lot of exceptions for CPA as it's part of generated 1000 campaigns in the test.
So , do we go with zero ?

**Comment by abushev** [comment]
@venediktov Yeah, let's do zero.

**Comment by abushev** [comment]
Well done

**Pull request merged**
